% MIT License
% 
% Copyright (c) 2024 Mohsen Alighanbari, Sina Alighanbari, Lisa Griffin
% 
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
% 
% The above copyright notice and this permission notice shall be included in all
% copies or substantial portions of the Software.
% 
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.

function Trait_Results = MVEE_Export_2d()
    % Input for the CoP and CoM optimization code model:
    diaWindow = dialog('Position', [300, 300, 510, 440], 'Name', 'Exporting Variables');
    % Q1:
    Text1 = uicontrol('Parent',diaWindow, ...
        'Style','text', ...
        'Position',[80 250 350 170], ...
        'String','What Variable do you want to be exported?', ...
        'FontWeight','bold','FontSize',12);
        opt1 = uicontrol('Parent',diaWindow, ...
            'Style','checkbox', ...
            'Position',[15 360 500 25], ...
            'String','Area of the ellipse with Optimization algorithm.', ...
            'FontSize',10);
        opt2 = uicontrol('Parent',diaWindow, ...
            'Style','checkbox', ...
            'Position',[15 330 500 25], ...
            'String','Area of the ellipse with data trimmer method.', ...
            'FontSize',10);
        opt3 = uicontrol('Parent',diaWindow,'Style','checkbox', ...
            'Position',[15 300 500 25],'String','Area of the ellipse with PCA technique.', ...
            'FontSize',10);
        opt4 = uicontrol('Parent',diaWindow,'Style','checkbox', ...
            'Position',[15 270 500 25],'String','Area of the ellipse with covarite technique.', ...
            'FontSize',10);
        opt5 = uicontrol('Parent',diaWindow,'Style','checkbox', ...
            'Position',[15 240 500 25], ...
            'String','Percentage of points inside the ellipse enclosed with the optimization algorithm.', ...
            'FontSize',10);
        opt6 = uicontrol('Parent',diaWindow,'Style','checkbox', ...
            'Position',[15 210 500 25], ...
            'String','Percentage of points inside the ellipse enclosed with the data trimmer method.', ...
            'FontSize',10);
        opt7 = uicontrol('Parent',diaWindow,'Style','checkbox', ...
            'Position',[15 180 500 25], ...
            'String','Percentage of points inside the ellipse enclosed wit the PCA method.', ...
            'FontSize',10);
        opt8 = uicontrol('Parent',diaWindow,'Style','checkbox', ...
            'Position',[15 150 500 25], ...
            'String','Run time for optimization algorithm.', ...
            'FontSize',10);
        opt9 = uicontrol ('Parent',diaWindow,'Style','checkbox', ...
            'Position',[15 120 500 25], ...
            'String','Run time for data trimmer method.', ...
            'FontSize',10);
        opt10 = uicontrol ('Parent',diaWindow,'Style','checkbox', ...
            'Position',[15 90 500 25], ...
            'String','Run time for PCA method.', ...
            'FontSize',10);
        opt11 = uicontrol ('Parent',diaWindow,'Style','checkbox', ...
            'Position',[15 60 500 25], ...
            'String','Run time for covariate method.', ...
            'FontSize',10);
    % make an Ok button:
    OkBtn = uicontrol('Parent',diaWindow,'Position',[230 10 70 25], ...
        'String','OK','Callback',@DialWinResponse);
    uiwait(diaWindow);

    function DialWinResponse(~,~)
        Trait_Results = struct();
        Trait_Results.SelectOptions = get_selected_option({opt1,opt2,opt3,opt4,opt5,opt6,opt7,opt8,opt9,opt10,opt11});
        delete(diaWindow);
    end
    function selected = get_selected_option(options)
        selected = {};
        for i=1:length(options)
            if get(options{i},'Value')== 1
                selected {i} = get(options{i},'String');
            end
        end
    end
end